# Generated by Django 6.0.2 on 2026-02-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_lead_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
