# Generated by Django 6.0.2 on 2026-03-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_lead_options_lead_owner_lead_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_creation',
            new_name='created_at',
        ),
    ]
