# Generated by Django 6.0.2 on 2026-03-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_lead_attechmant_alter_lead_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='attechmant',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
