# Generated by Django 6.0.2 on 2026-03-18 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_lead_attechmant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='attechmant',
            new_name='attechment',
        ),
    ]
