# Generated by Django 6.0.2 on 2026-03-18 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_rename_attechmant_lead_attechment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='attechment',
            new_name='attachment',
        ),
    ]
